### ISSUE TITLE
Deal with PromptGameFinder  when running from Mod Manager

### ISSUE THREAD

**Issue by Raicuparta** [ow-mods/owml#286]
When no game path is found, PromptGameFinder will ask for the path via console input. This doesn't work with the mod manager.

We could send a different message type so the mod manager can deal with it better. Or we use #254, which would make the mod manager show an alert explaining what to do (change game path in settings).

**Comment by misternebula** [comment]
Don't need to - the console stays open, and you type the path there. The console then closes as normal after it gets the game path.

This was probably fixed by accident by either the manager or OWML at some point.
