### ISSUE TITLE
InputPopup steals input devices and never gives them back

### ISSUE THREAD

**Issue by A9G-Data-Droid** [ow-mods/owml#385]
If I open a custom input popup from the save menu I see the popup text and the pause menu text at the same time. I interact with both, which is an issue unto itself. Once both the popup and the pause menu are closed I can no longer look around with mouse or gamepad. I'm stuck in the mouse mode as if the input still belongs to `ModHelper.Menus` and not the game. The only way out is to quit the game. Full bork.

The calling code is doing this:
`var popup = ModHelper.Menus.PopupManager.CreateInputPopup`

**Comment by TAImatem** [comment]
Partially fixed by merge #404, but Pause menu and input popup still both seem to be interactable at the same time, so closing Pause menu before the popup will probably yield similar results
