### ISSUE TITLE
[Request] Steam Deck compatibility

### ISSUE THREAD

**Issue by pakoito** [ow-mods/owml#521]
Coming from: https://github.com/ow-mods/ow-mod-manager/issues/180

As Outer Wilds is compatible with Steam Deck out of the box, it'd be great if mods loaded with OWML were too :D

**Comment by TAImatem** [comment]
Did you try using instructions for running under Proton from other, more universal, modloaders like Melon? In case of Melon instructions you might have to try using higher versions of dotnet though, as the initial patcher (console app) relies on Net Framework 4.8

**Comment by pakoito** [comment]
I'm afraid not, I didn't even know about Melon until now.

**Comment by TAImatem** [comment]
seems like it most probably won't work by simply just adjusting those protontricks settings. Both Melon and BepInEx use what is know as "Proxy dll" to start modloader, while we patch game's dlls with a separate application. I guess it might work if you grab patched dll from Windows install or somehow get the patcher (the console .exe app) to work on Linux

**Comment by Bwc9876** [comment]
Steam deck compatibility (and better Linux compatibility in general) is fully implemented in [the new mod manager](https://github.com/Bwc9876/ow-mod-man/tree/main/owmods_gui). It can be gotten directly from the "Discover" app in desktop mode or you can click [this link](https://flathub.org/apps/com.outerwildsmods.owmods_gui) and download the flatpak ref file to install it. The manager itself needs Mono but if you're installing via flatpak (or Discover), then it'll be bundled automatically.

**Comment by pakoito** [comment]
Yoooooooooooo
