### ISSUE TITLE
[Request] Add explanation for settings in config menu like in base game menus

### ISSUE THREAD

**Issue by Owen013** [ow-mods/owml#529]
![1](https://user-images.githubusercontent.com/96493201/231226682-88746a97-5bbc-4dbf-9f89-398b09741ca1.png)
![2](https://user-images.githubusercontent.com/96493201/231226686-3ae3693b-3610-421f-a4ee-4523d4b9a032.png)

**Comment by MegaPiggy** [comment]
That already exists! It is the tooltip property in the [schema](https://github.com/ow-mods/owml/blob/32d34e9a12dfa30a47fbcf1b3659d57021556e35/schemas/config_schema.json#L72).

**Comment by Owen013** [comment]
I am idiot. Thank you
