### ISSUE TITLE
Add translation support for config options

### ISSUE THREAD

**Issue by GameWyrm** [ow-mods/owml#578]
Make it so that OWML can read `translations\[selected language].json` to get translation info for the titles and descriptions of config settings. I would put these in UIDictionary personally.

**Comment by GameWyrm** [comment]
It doesn't look like I can add labels to my own issues here but this is a feature request/enhancement

**Comment by xen-42** [comment]
To clarify you're wanting OWML to use the same translation json system as NH? Since serializing dictionaries for UI, shiplog etc to json is an NH invention.

**Comment by GameWyrm** [comment]
Ah, didn’t realize those were NH features. However, unless there’s a technical reason/advantage to having multiple translation files, I don’t see why not to just reuse NH’s file.
